#! /usr/bin/python
###############################################################################
# This script is used to create co information database.
# Writen by: Jim Zeng 2015-08-04
###############################################################################

import re
import datetime
import sys
import os
import MySQLdb
import json
from pprint import pprint
import urllib
import urllib2

vendorCount = {}
#for root, dirs, files in os.walk("/home/jzeng/projects/cvelist"):
opener = urllib.FancyURLopener({})
headers = { 'User-Agent' : 'Mozilla/5.0' }
fileCount = 0
stateStats = {}
for root, dirs, files in os.walk("/home/jzeng/projects/cvelist/2017/7xxx"):
    #print root
    for file in files:
        #print file
        if not file.endswith('.json'):
            continue
        fileCount += 1

        #if fileCount > 40:
        #    break 

        fullName = root + "/" + file 
        with open(fullName) as data_file:    
            data = json.load(data_file)
            vendorName = ''
            state = ''
            url = ''
            try: 
                vendorName =  data['CVE_data_meta']['ASSIGNER'] 
                state = data['CVE_data_meta']['STATE']
                try:
                    stateStats[state] +=1
                except:
                    stateStats[state] = 1
                if state != 'PUBLIC':
                    continue
                #print file
                url =  data['references']['reference_data'][0]['url'] 
                #print url
                req = urllib2.Request(url, None, headers)
                status = urllib2.urlopen(req).code
                if status != 200:
                    print file, url
                    print status
            except:
                print file, url 
                pass


print "======================="
print "Total CVEs: ", fileCount 
allStates = stateStats.keys()
for state in allStates:
    print state, ":", stateStats[state]
